@startuml
start
:Người dùng yêu cầu đặt lại mật khẩu/ quên mật khẩu;
:Nhập Email;

if (Kiểm tra định dạng và tồn tại) then (Hợp lệ)
  :Hệ thống gửi mã OTP qua Email;
  partition "AC02: Xác thực OTP" {
    :Thực hiện xác thực OTP và đặt mật khẩu mới;
  }
  :Thông báo thành công;
  :Chuyển hướng về trang Đăng nhập;
  stop
else (Email không tồn tại/Chưa xác thực)
  :Thông báo lỗi;
  stop
endif
@enduml
